# -*- coding: utf-8 -*-
#
# This file is part of Zenodo.
# Copyright (C) 2015 CERN.
#
# Zenodo is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# Zenodo is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Zenodo; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.
#
# In applying this license, CERN does not
# waive the privileges and immunities granted to it by virtue of its status
# as an Intergovernmental Organization or submit itself to any jurisdiction.

addons:
  postgresql: "9.4"
  apt:
    packages:
      - nodejs
      - libfreetype6-dev

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8d72dd7ee741cd5e98c6
    on_success: change  always
    on_failure: always  always
    on_start: never     always

sudo: false

language: python

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.nvm

services:
  - postgresql
  - redis
  - rabbitmq

env:
  - REQUIREMENTS=prod E2E="no" SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/zenodo" ES_URL="https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/2.2.0/elasticsearch-2.2.0.tar.gz"
  - REQUIREMENTS=latest E2E="no" SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/zenodo" ES_URL="https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.2.2.tar.gz"
  - REQUIREMENTS=prod E2E="no" SQLALCHEMY_DATABASE_URI="sqlite:///zenodo.db" ES_URL="https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/2.2.0/elasticsearch-2.2.0.tar.gz"
  - REQUIREMENTS=prod E2E="yes" SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/zenodo" ES_URL="https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/2.2.0/elasticsearch-2.2.0.tar.gz"

jdk:
  - "oraclejdk8"

python:
  - "2.7"
  - "3.5"

matrix:
  fast_finish: true
  allow_failures:
    - env: REQUIREMENTS=latest E2E="no" SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/zenodo" ES_URL="https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.2.2.tar.gz"

before_install:
  - "mkdir /tmp/elasticsearch"
  - "wget -O - $ES_URL | tar xz --directory=/tmp/elasticsearch --strip-components=1"
  # - "/tmp/elasticsearch/bin/plugin install -b mapper-attachments"
  - "/tmp/elasticsearch/bin/plugin install -b ingest-attachments"
  - "/tmp/elasticsearch/bin/elasticsearch &"
  - "travis_retry pip install --upgrade pip setuptools py 'sphinx==1.4.4'"
  - "travis_retry pip install wheel coveralls requirements-builder"
  - "./scripts/setup-npm.sh"
  - "cat requirements.txt > .travis-prod-requirements.txt"
  - "requirements-builder --level=pypi setup.py > .travis-latest-requirements.txt"

install:
  - "travis_retry pip install -r .travis-${REQUIREMENTS}-requirements.txt --pre"
  - "travis_retry pip install -e .[all,postgresql] --pre"
  - "./scripts/setup-assets.sh"

before_script:
  - "if [ ${E2E} == 'yes' ]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; export E2E_WEBDRIVER_BROWSERS='Firefox'; fi"
  # Allow ES to start
  - sleep 10

script:
  - "if [ ${E2E} == 'yes' ]; then py.test tests/e2e/; else ./run-tests.sh; fi"

after_success:
  - coveralls
