blank_issues_enabled: true
contact_links:
  - name: Frequently asked questions ðŸ“ƒ
    url: https://help.zenodo.org
    about: Questions regarding Zenodo? Take a look at our FAQs
  - name: Developer documentation ðŸ’»
    url: https://developers.zenodo.org/
    about: Other type of issue? Ask for support
  - name: Support questions ðŸ’¬
    url: https://zenodo.org/support
    about: Other type of issue? Ask for support
